pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/mathurangy/Devops-Repository.git'
            }
        }

        stage('Install Backend') {
            steps {
                dir('DaycareWaitlist/backend') {
                    bat 'npm install'
                }
            }
        }

        stage('Install Frontend') {
            steps {
                dir('DaycareWaitlist/frontend') {
                    bat 'npm install'
                }
            }
        }

        stage('Build') {
            steps {
                dir('DaycareWaitlist/frontend') {
                    bat 'npm run build || echo No build step'
                }
            }
        }

        stage('Test') {
            steps {
                dir('DaycareWaitlist/backend') {
                    bat 'npm test || echo No tests found'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                bat 'echo Running static code analysis (mock SonarQube)...'
            }
        }

        stage('Deliver') {
    steps {
        bat 'echo Packaging application...'
        bat 'echo Artifact created successfully'
    }
}

        stage('Deploy to Dev') {
            steps {
                bat 'echo Deploying to DEV environment...'
            }
        }

        stage('Deploy to QAT') {
            steps {
                bat 'echo Deploying to QAT environment...'
            }
        }

        stage('Deploy to Staging') {
            steps {
                bat 'echo Deploying to STAGING environment...'
            }
        }

        stage('Deploy to Production') {
            steps {
                bat 'echo Deploying to PRODUCTION environment...'
            }
        }
    }
}
